// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmN9lpu7rAfed88MuuMFx4RlPNdq9g2Z4',
    appId: '1:871958775721:web:3eddbdae0359245a4866b8',
    messagingSenderId: '871958775721',
    projectId: 'mobileproject-19b42',
    authDomain: 'mobileproject-19b42.firebaseapp.com',
    databaseURL: 'https://mobileproject-19b42-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mobileproject-19b42.appspot.com',
    measurementId: 'G-SMWFYB75BN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkW_zFti-k4iANGgV_hgNlCfbSgW0Qor0',
    appId: '1:871958775721:android:5c9f58e06a3582034866b8',
    messagingSenderId: '871958775721',
    projectId: 'mobileproject-19b42',
    databaseURL: 'https://mobileproject-19b42-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mobileproject-19b42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASMlvc7_yn8OkOMrCYbJDtqugSq17uUYI',
    appId: '1:871958775721:ios:5bba0dc78f12d08e4866b8',
    messagingSenderId: '871958775721',
    projectId: 'mobileproject-19b42',
    databaseURL: 'https://mobileproject-19b42-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mobileproject-19b42.appspot.com',
    iosBundleId: 'com.example.mobileproject',
  );
}
